"""Builder functions for conversation.json entry dicts.

Every entry carries a ``type`` discriminator and a UTC ISO-8601 ``timestamp``.
These helpers ensure a consistent shape so the rest of the codebase never has
to hand-craft entry dicts.
"""

from datetime import datetime, timezone


def _now_iso() -> str:
    """Return the current UTC time as an ISO-8601 string."""
    return datetime.now(timezone.utc).isoformat()


def make_message_entry(role: str, content: str) -> dict:
    """Create a conversational message entry.

    Args:
        role: ``"user"`` or ``"assistant"``.
        content: The message text.
    """
    return {
        "type": "message",
        "role": role,
        "content": content,
        "timestamp": _now_iso(),
    }


def make_tool_call_entry(agent: str, prompt: str) -> dict:
    """Create a tool-call entry recording a sub-agent invocation.

    Args:
        agent: The agent identifier (e.g. ``"trip_advisor"``).
        prompt: The plain text prompt passed to the sub-agent.
    """
    return {
        "type": "tool_call",
        "agent": agent,
        "prompt": prompt,
        "timestamp": _now_iso(),
    }


def make_tool_result_entry(agent: str, response: str) -> dict:
    """Create a tool-result entry recording a sub-agent's plain text response.

    Args:
        agent: The agent identifier.
        response: The plain text response returned by the sub-agent.
    """
    return {
        "type": "tool_result",
        "agent": agent,
        "response": response,
        "timestamp": _now_iso(),
    }


def make_checkpoint_entry(checkpoint_num: int, label: str, approved_data: dict) -> dict:
    """Create a checkpoint entry recording a user approval decision.

    Args:
        checkpoint_num: The checkpoint number (1, 2, or 3).
        label: A human-readable label (e.g. ``"travel_plan_approved"``).
        approved_data: The data that was approved at this checkpoint.
    """
    return {
        "type": "checkpoint",
        "checkpoint": checkpoint_num,
        "label": label,
        "approved": approved_data,
        "timestamp": _now_iso(),
    }


def make_snapshot_entry(snapshot_id: int, summary: str) -> dict:
    """Create a compaction snapshot entry.

    Snapshots are generated by an LLM when context usage exceeds 30% of
    the context window.  The ``summary`` field contains a comprehensive
    9-section structured summary produced via
    ``conversation_compaction.prompt.md``.

    Args:
        snapshot_id: The snapshot identifier (auto-incrementing).
        summary: The 9-section structured summary text.
    """
    return {
        "type": "snapshot",
        "snapshot_id": snapshot_id,
        "summary": summary,
        "timestamp": _now_iso(),
    }
